backend:
  name: github
  repo: Glen-Taylor37/Portfolio-Site
  branch: main

media_folder: 'static/images/uploads'
public_folder: 'images'

collections:
  - name: 'art'
    label: 'Art'
    folder: '_gallery/art'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'gallery'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Image', name: 'image', widget: 'image'}